ruby: &ruby
  image: carwow/ruby-ci:2.4.2

elasticsearch_container: &elasticsearch_container
  image: carwow/elasticsearch-ci:5.5.1

version: 2
jobs:
  bundle:
    working_directory: ~/es_index
    docker:
      - *ruby
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run: |
          bundle config --local path vendor/bundle &&
          bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: [~/es_index/vendor/bundle]
      - persist_to_workspace:
          root: '~'
          paths: [es_index]

  rubocop:
    working_directory: ~/es_index
    docker:
      - *ruby
    steps:
      - attach_workspace:
          at: '~'
      - run: bundle exec rubocop

  tests:
    working_directory: ~/es_index
    docker:
      - *ruby
      - *elasticsearch_container
    steps:
      - attach_workspace:
          at: '~'
      - run: |
          bundle exec rspec --pattern "**/*_spec.rb" --format "progress"
  publish:
    working_directory: ~/es_index
    docker:
      - *ruby
    steps:
      - attach_workspace:
          at: '~'
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 0700 ~/.ssh/known_hosts
          git config user.name 'CircleCI'
          git config user.email 'developers@carwow.co.uk'
          bundle exec rake release

workflows:
  version: 2
  build-and-publish:
    jobs:
      - bundle
      - rubocop:
          requires: [bundle]
      - tests:
          requires: [bundle]
      - publish:
          requires: [rubocop, tests]
          filters:
            branches:
              only: [master]
